### ISSUE TITLE
Why is the release 118 MB?

### ISSUE THREAD

**Issue by mmontag** [Osmose/moseamp#2]
Was very excited about this, then I saw the footprint of the binary. But maybe I can be convinced this is no concern. What's in there taking up so many bytes?

**Comment by Osmose** [comment]
Well I'm only a year and a half late responding, whoops. :P (I didn't have notifications on for the repo yet)

Anywho, to answer your question, MoseAmp is an Electron app, so most of the size is the Electron runtime and various dependencies. 

I suspect there's some megabytes to be shaved off by bundling stuff from `node_modules` (which we currently don't) but as long as we're an Electron app the app size is gonna be on the scale of tens of megabytes.

Upside is, I know how to make webpages so the UI is pretty. :P 

If you're really concerned about file size I'd recommend looking into something like https://github.com/sasq64/chipmachine.

Thanks for the question!
